default:
  before_script:
    - docker info

.parallel:
  parallel:
    matrix:
      - DEV_CONTAINER: [cloud-developer]

variables:
  GOOGLE_PROJECT: psi-de-0-cicd-poc-0
  GOOGLE_CREDENTIALS: cicd-sa-credentials.json
  SERVICE_ACCOUNT: gitlab-ci-1@${GOOGLE_PROJECT}.iam.gserviceaccount.com
  WIF_PROVIDER: projects/504787948326/locations/global/workloadIdentityPools/psi-de-0-bootstrap/providers/psi-de-0-bootstrap-git-psi

stages:
  - gcp-setup
  - build
  - test

gcp-setup:
  stage: gcp-setup
  image:
    name: google/cloud-sdk:slim
  artifacts:
    paths:
      - $GOOGLE_CREDENTIALS
  id_tokens:
    GITLAB_TOKEN:
      aud: https://gitlab.com
  before_script:
    - echo "${GITLAB_TOKEN}" > token.txt
  script:
    - |
      gcloud iam workload-identity-pools create-cred-config "${WIF_PROVIDER}" \
        --service-account="${SERVICE_ACCOUNT}" \
        --output-file="${GOOGLE_CREDENTIALS}" \
        --credential-source-file="token.txt"
    - gcloud config set auth/credential_file_override "${GOOGLE_CREDENTIALS}"
    - gcloud config set project "${GOOGLE_PROJECT}"

build_image:
  extends: .parallel
  stage: build
  script:
    - docker build ${DEV_CONTAINER}/ -t europe-west3-docker.pkg.dev/${GOOGLE_PROJECT}/container-images/devcontainers/${DEV_CONTAINER}:1

sast:
  extends: .parallel
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
