variables:
  GOOGLE_PROJECT: psi-de-0-cicd-poc-0
  # variable name is significant (see: https://cloud.google.com/docs/authentication/provide-credentials-adc#wlif)
  GOOGLE_APPLICATION_CREDENTIALS: application_default_credentials.json
  SERVICE_ACCOUNT: gitlab-ci-1@${GOOGLE_PROJECT}.iam.gserviceaccount.com
  WIF_PROVIDER: projects/504787948326/locations/global/workloadIdentityPools/psi-de-0-bootstrap/providers/psi-de-0-bootstrap-git-psi
  PUSH_FLAG: false

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        PUSH_FLAG: true
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        PUSH_FLAG: false
    - if: $CI_PIPELINE_SOURCE == "push"
      variables:
        PUSH_FLAG: false

stages:
  - init
  - build

setup-gcp:
  stage: init
  image:
    name: google/cloud-sdk:slim
  artifacts:
    paths:
      - $GOOGLE_APPLICATION_CREDENTIALS
  id_tokens:
    GITLAB_TOKEN:
      aud: https://gitlab.com
  before_script:
    - echo "${GITLAB_TOKEN}" > token.txt
  script:
    - gcloud iam workload-identity-pools create-cred-config "${WIF_PROVIDER}"
      --service-account="${SERVICE_ACCOUNT}"
      --output-file="${GOOGLE_APPLICATION_CREDENTIALS}"
      --credential-source-file="token.txt"
    - gcloud config set auth/credential_file_override "${GOOGLE_APPLICATION_CREDENTIALS}"
    - gcloud config set project "${GOOGLE_PROJECT}"

build-images:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  dependencies:
    - setup-gcp
  id_tokens:
    GITLAB_TOKEN:
      aud: https://gitlab.com
  variables:
    VERSION: 2.1.25
    OS: linux
    ARCH: amd64
    REGISTRY: europe-west3-docker.pkg.dev
  script:
    - docker build cloud-developer/ -t ${REGISTRY}/${GOOGLE_PROJECT}/container-images/devcontainers/cloud-developer
    - >
      if [ "$PUSH_FLAG" == "true" ]; then
        wget -q "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${VERSION}/docker-credential-gcr_${OS}_${ARCH}-${VERSION}.tar.gz" -O - \
          | tar xz docker-credential-gcr && \
        chmod +x docker-credential-gcr && mv docker-credential-gcr /usr/bin/
        docker-credential-gcr configure-docker --registries=${REGISTRY}
        echo "$GITLAB_TOKEN" > token.txt
        docker push ${REGISTRY}/${GOOGLE_PROJECT}/container-images/devcontainers/cloud-developer
      fi
